CREATE TABLE [Addresses] (
[Id] INT PRIMARY KEY IDENTITY NOT NULL,
[Town] VARCHAR(30) NOT NULL,
[Country] NVARCHAR(30) NOT NULL,
[Streat] NVARCHAR(100) NOT NULL,
[ZIP] VARCHAR(20) NOT NULL)

CREATE TABLE [Sizes] (
[Id] INT PRIMARY KEY IDENTITY NOT NULL,
[Length] INT NOT NULL,
CHECK(LEN([Length]) BETWEEN 10 AND 25),
[RingRange] DECIMAL (3,2) NOT NULL
CHECK(LEN([RingRange]) BETWEEN 1.5 AND 7.5))

CREATE TABLE [Tastes] (
[Id] INT PRIMARY KEY IDENTITY NOT NULL,
[TasteType] VARCHAR(20) NOT NULL,
[TasteStrength] VARCHAR(15) NOT NULL,
[ImageURL] NVARCHAR(100) NOT NULL)

CREATE TABLE [Brands] (
[Id] INT PRIMARY KEY IDENTITY NOT NULL,
[BrandName] VARCHAR(30) NOT NULL UNIQUE,
[BrandDescription] VARCHAR(MAX))

CREATE TABLE [Clients] (
[Id] INT PRIMARY KEY IDENTITY NOT NULL,
[FirstName] NVARCHAR(30) NOT NULL,
[LastName] NVARCHAR(30) NOT NULL,
[Email] NVARCHAR(50) NOT NULL,
[AddressId] INT FOREIGN KEY REFERENCES
            [Addresses]([Id]) NOT NULL)

CREATE TABLE [Cigars] (
[Id] INT PRIMARY KEY IDENTITY NOT NULL,
[CigarName] VARCHAR(80) NOT NULL,
[BrandId] INT FOREIGN KEY REFERENCES [Brands]([Id]) NOT NULL,
[TastId] INT FOREIGN KEY REFERENCES [Tastes] ([Id]) NOT NULL,
[SizeId] INT FOREIGN KEY REFERENCES [Sizes] ([Id]) NOT NULL,
[PriceForSingleCigar] DECIMAL (4,2) NOT NULL,
[ImageURL] NVARCHAR(100) NOT NULL)



CREATE TABLE [ClientsCigars] (
[ClientId] INT FOREIGN KEY REFERENCES [Clients] ([Id]),
[CigarId] INT FOREIGN KEY REFERENCES [Cigars]([Id]),
PRIMARY KEY ([ClientId], [CigarId]))
